[project]
name = "ezviz-smartplug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyezvizapi>=1.0.1.0",
]

[dependency-groups]
dev = [
    "homeassistant>=2025.4.4",
    "pyright>=1.1.403",
    "ruff>=0.12.4",
]
